
  CREATE TABLE "MEDI_TRACK"."STOCK_ADJUSTMENTS"
   (    "ID" NUMBER(19,0) NOT NULL ENABLE,
        "MEDICINE_ID" NUMBER(19,0) NOT NULL ENABLE,
        "USER_ID" NUMBER(19,0) NOT NULL ENABLE,
        "TYPE" VARCHAR2(255) NOT NULL ENABLE,
        "QUANTITY" NUMBER(10,0) NOT NULL ENABLE,
        "REASON" VARCHAR2(255),
        "CREATED_AT" TIMESTAMP (6),
        "UPDATED_AT" TIMESTAMP (6),
         CHECK ("TYPE" in ('increase', 'decrease')) ENABLE,
         CONSTRAINT "STOCK_ADJUSTMENTS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
         CONSTRAINT "STOC_ADJUSTMENT_MEDICIN_ID_FK" FOREIGN KEY ("MEDICINE_ID")
          REFERENCES "MEDI_TRACK"."MEDICINES" ("ID") ON DELETE CASCADE ENABLE,
         CONSTRAINT "STOCK_ADJUSTMENTS_USER_ID_FK" FOREIGN KEY ("USER_ID")
          REFERENCES "MEDI_TRACK"."USERS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DE
FAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

SQL> SPOOL OFF
SQL> HOST cd
C:\Users\rifaa\Desktop\app\oracle\product\11.2.0\server\bin

SQL> SPOOL categories_schema.sql
SQL> SELECT DBMS_METADATA.GET_DDL('TABLE', 'CATEGORIES') FROM DUAL;

CREATE TABLE categories (
    id NUMBER(19,0) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    description CLOB,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),

    CONSTRAINT categories_id_pk PRIMARY KEY (id)
);