SET LONG 5000
SET PAGESIZE 0
SET LINESIZE 200
SET FEEDBACK OFF

SPOOL categories_schema.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'CATEGORIES') FROM DUAL;
SPOOL OFF

SPOOL suppliers_schema.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'SUPPLIERS') FROM DUAL;
SPOOL OFF

SPOOL medicines_schema.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'MEDICINES') FROM DUAL;
SPOOL OFF

SPOOL customers_schema.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'CUSTOMERS') FROM DUAL;
SPOOL OFF

SPOOL users_schema.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'USERS') FROM DUAL;
SPOOL OFF

SPOOL sales_schema.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'SALES') FROM DUAL;
SPOOL OFF

SPOOL sale_items_schema.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'SALE_ITEMS') FROM DUAL;
SPOOL OFF

SPOOL purchases_schema.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PURCHASES') FROM DUAL;
SPOOL OFF

SPOOL purchase_items_schema.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PURCHASE_ITEMS') FROM DUAL;
SPOOL OFF

SPOOL prescriptions_schema.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'PRESCRIPTIONS') FROM DUAL;
SPOOL OFF

SPOOL stock_adjustments_schema.sql
SELECT DBMS_METADATA.GET_DDL('TABLE', 'STOCK_ADJUSTMENTS') FROM DUAL;
SPOOL OFF